### ISSUE TITLE
Build Issues with 8.3 and XCode 6.3.1 with Ti SDK 4.0.0.GA

### ISSUE THREAD

**Issue by stereoket** [olofmagnusson/healthkit-titanium-module#2]
Hi,

I'm trying to get your module working, and although I can build with the python script and include the module in my project, the app won't build as inclusion of the module leads to this error:

[ERROR] 2015-06-16 23:35:33.299 xcodebuild[17804:619882]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/ketan/Library/Developer/Xcode/DeveloperPortal%206.3.1.db).
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld build/Debug-iphonesimulator/Koffeeology.app/Koffeeology normal i386
[ERROR] (1 failure)

I've tried building the XCode project directly, rebuilding the module in XCode and with the latest TiSDK - but am not getting any luck. Do you have any info on which environments this *should* work in?

Thanks

**Comment by stereoket** [comment]
For more information on this, I get about 200 link errors if I try and build this from within xcode, its a vanilla app that just includes the module.

**Comment by olofmagnusson** [comment]
Try to build the app on a real device instead of the simulator. That's what I had to do.

**Comment by stereoket** [comment]
Thanks for the info, I've just done that and I can get it working from device, although I have to build the app via Xcode as it wont build directly from Studio or the CLI. I'll mess around with it a bit and see if I can get it doing what I want.

It would be good to find out what is stopping it from building against the Sim, as the simulator has the Health app bundled into it.

Thanks for sharing the module, appreciate it.
